name = "meta-messenger"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Static assets (frontend)
assets = { directory = "public", binding = "ASSETS" }

# KV Namespaces
[[kv_namespaces]]
binding = "MESSAGES_KV"
id = "3ecdb75c0eca40879b66fae501fb3560"

[[kv_namespaces]]
binding = "USERS_KV"
id = "f76099536cac49388a30b5d0fe730834"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "eaf3857f7b9a410984e5f782ec4aba05"

[vars]
APP_NAME = "Meta Messenger"
